import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { AuthProvider } from "../../contexts/AuthContext";
import CustomThemeProvider from "../../components/providers/ThemeProvider";
import { LanguageProvider } from "../../contexts/LanguageContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sogang = localFont({
  src: '../../public/fonts/SOGANG_UNIVERSITY_for_windows.ttf',
  variable: '--font-sogang',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sogang.variable} font-sogang antialiased`}
      >
        <CustomThemeProvider>
          <LanguageProvider>
            <AuthProvider>
              {children}
            </AuthProvider>
          </LanguageProvider>
        </CustomThemeProvider>
      </body>
    </html>
  );
}
